apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  selector:
    matchLabels: # has to match .spec.template.metadata.labels
      app: mysql 
      openebs.io/target-affinity: mysql-sts
      openebs.io/replica-anti-affinity: mysql-sts
  serviceName: "mysql"
  replicas: 3
  template:
    metadata:
      labels: # has to match .spec.selector.matchLabels
        app: mysql 
        openebs.io/target-affinity: mysql-sts
        openebs.io/replica-anti-affinity: mysql-sts
    spec:
      containers:
      - name: mysql
        image: mysql:3.3.2
        ports:
        - containerPort: 5984
        env:
        - name: mysql_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: mysql_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password  
        volumeMounts:
        - name: mysql-volume
          mountPath: /data/mysql
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: default-jiva-csi-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
spec:
  selector:
    app: mysql
  clusterIP: None  
  ports:
    - protocol: TCP
      port: 5984
      targetPort: 5984
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-external-service
spec:
  selector:
    app: mysql 
  ports:
    - protocol: TCP
      port: 5984
      targetPort: 5984