apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb-statefulset
spec:
  selector:
    matchLabels: # has to match .spec.template.metadata.labels
      app: couchdb 
      openebs.io/target-affinity: couchdb-sts
      openebs.io/replica-anti-affinity: couch-sts
  serviceName: "couchdb"
  replicas: 3
  template:
    metadata:
      labels: # has to match .spec.selector.matchLabels
        app: couchdb 
        openebs.io/target-affinity: couchdb-sts
        openebs.io/replica-anti-affinity: couch-sts
    spec:
      containers:
      - name: couchdb
        image: couchdb:3.3.2
        ports:
        - containerPort: 5984
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: couchdb-user
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: couchdb-password  
        volumeMounts:
        - name: couchdb-volume
          mountPath: /data/couchdb
      volumes:
      - name: couchdb-volume
        persistentVolumeClaim:
          claimName: default-jiva-csi-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: couchdb-service
spec:
  selector:
    app: couchdb
  ports:
    - protocol: TCP
      port: 5984
      targetPort: 5984