# Generated by Django 4.2 on 2023-05-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=3)),
                ('accuracy', models.FloatField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
