# Generated by Django 4.2.1 on 2023-05-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_pic_delete_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('type', models.BooleanField()),
                ('accuracy', models.IntegerField(max_length=3)),
                ('bid', models.IntegerField()),
            ],
        ),
    ]
