# Generated by Django 4.2.1 on 2023-05-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0004_alter_pet_accuracy_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.CharField(max_length=10000000),
        ),
    ]
