# Generated by Django 4.2.1 on 2023-05-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0005_alter_pet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='time',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='type',
        ),
        migrations.AddField(
            model_name='pet',
            name='foreignKey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pics.pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pic',
            name='picture',
            field=models.CharField(default='test', max_length=10000000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pic',
            name='time',
            field=models.CharField(max_length=8),
        ),
    ]
