# Generated by Django 4.2.1 on 2023-06-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0006_remove_pet_date_remove_pet_image_remove_pet_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='accuracy',
            field=models.FloatField(),
        ),
    ]
