apiVersion: v1
kind: Service
metadata:
  name: restapi-svc
spec:
  selector:
    app: restapi
  ports:
    - protocol: TCP
      port: 3200 #TODO
      targetPort: 3200 #TODO
  type: LoadBalancer
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
spec:
  selector:
    matchLabels:
      app: restapi 
  replicas: 3
  template:
    metadata:
      labels:
        app: restapi
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - restapi
            topologyKey: kubernetes.io/hostname
      containers:
      - name: restapi
        image: skywalker360/flask_pd:1.41 #TODO
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3200 #TODO
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: restapi-secret
              key: telegram-bot-token
        - name: TELEGRAM_CHAT_ID
          valueFrom:
            secretKeyRef:
              name: restapi-secret
              key: telegram-group-chat-id
        - name: MONGO_INITDB_CONFIG #TODO
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url